export const WORKOUT_PLAN_FULL = {
  "Week 1 - Day 1": [
    "Warm-Up: 5-10 min treadmill walk/jog + dynamic stretches (leg swings, arm circles, hip rotations, light bodyweight squats)",
    "Barbell Back Squat 3x8 (heavy, ~2 min rest)",
    "Superset 1A: Bent-Over Barbell Row 3x10",
    "Superset 1B: DB Overhead Press 3x10",
    "Superset 2A: Leg Curl 3x12",
    "Superset 2B: Plank 3x30s",
    "Cardio: Elliptical 10 min moderate pace (RPE 6-7/10)",
    "Cool-Down: Light walk + static stretches for quads, hamstrings, glutes, shoulders (hold each 20-30s)",
  ],
  "Week 1 - Day 2": [
    "Warm-Up: 5 min rowing/cycling + dynamic stretches (arm swings, trunk twists, leg swings, shoulder rolls)",
    "Barbell Bench Press 3x6-8 (heavy, ~2 min rest)",
    "Superset 1A: DB Walking Lunge 3x10 each leg",
    "Superset 1B: One-Arm DB Row 3x10 each arm",
    "Superset 2A: Cable Triceps Pushdown 2x12",
    "Superset 2B: DB Biceps Curl 2x12",
    "Core: Russian Twist 3x15 each side",
    "Cardio: Treadmill HIIT - 5 rounds (1 min fast run RPE 8-9/10, 1 min walk recovery)",
    "Cool-Down: 3-5 min walk + stretches for chest, shoulders, legs, hips",
  ],
  "Week 1 - Day 3": [
    "Warm-Up: 5 min rowing/elliptical + dynamic moves (hip circles, leg swings, light deadlift practice)",
    "Barbell Deadlift 3x6-8 (heavy, ~2 min rest)",
    "Superset 1A: Lat Pulldown 3x10",
    "Superset 1B: Incline DB Press 3x10",
    "Superset 2A: DB Step-Up 3x10 each leg",
    "Superset 2B: Side Plank 3x30s each side",
    "Cardio: Rowing Intervals - 10 min (1 min fast, 1 min easy)",
    "Cool-Down: Light walk + stretches for hamstrings, glutes, lower back, chest (hold 20-30s each)",
  ],
  "Week 2 - Day 1": [
    "Warm-Up: 5-10 min treadmill jog + dynamic stretches (emphasize squat mobility)",
    "Barbell Back Squat 3x8 (increase weight from Week 1, ~2 min rest)",
    "Superset 1A: Bent-Over Row 3x10 (focus on controlled form)",
    "Superset 1B: DB Overhead Press 3x10",
    "Superset 2A: Leg Curl 3x12 (increase weight if possible)",
    "Superset 2B: Plank 3x35s (5s longer than Week 1)",
    "Cardio: Elliptical 12 min moderate pace (RPE 7/10)",
    "Cool-Down: Static stretches for legs, back, shoulders (hold each 30s)",
  ],
  "Week 2 - Day 2": [
    "Warm-Up: 5 min rowing + mobility work (shoulder prep, hip openers)",
    "Barbell Bench Press 3x6-8 (increase weight from Week 1, ~2 min rest)",
    "Superset 1A: DB Walking Lunge 3x12 each leg (2 more reps/side)",
    "Superset 1B: One-Arm DB Row 3x10 each arm",
    "Superset 2A: Cable Triceps Pushdown 2x12 (increase weight)",
    "Superset 2B: DB Biceps Curl 2x12",
    "Core: Russian Twist 3x20 (5 more reps/side)",
    "Cardio: Treadmill Intervals - 6 rounds (1 min fast, 1 min walk)",
    "Cool-Down: 5 min walk + stretches (chest, back, legs)",
  ],
  "Week 2 - Day 3": [
    "Warm-Up: 5 min elliptical + dynamic prep (focus on hip hinge pattern)",
    "Barbell Deadlift 3x6-8 (increase weight from Week 1, ~2 min rest)",
    "Superset 1A: Lat Pulldown 3x10 (increase weight if form allows)",
    "Superset 1B: Incline DB Press 3x10",
    "Superset 2A: Step-Ups 3x10 each leg (controlled tempo)",
    "Superset 2B: Side Plank 3x35s each side (5s longer)",
    "Cardio: Rowing Intervals - 10 min (40s hard, 20s easy)",
    "Cool-Down: Thorough full body stretch focusing on posterior chain",
  ],
  "Week 3 - Day 1": [
    "Warm-Up: 5 min treadmill jog, dynamic mobility",
    "Back Squat 3x8 (add weight)",
    "Bent-Over Row 3x10",
    "DB Overhead Press 3x10",
    "Leg Curl 3x12",
    "Plank 3x40s",
    "Elliptical 12 min (higher resistance)",
    "Cool-Down: Stretch full posterior chain",
  ],
  "Week 3 - Day 2": [
    "Warm-Up: 5 min row, shoulder circles, hip mobility",
    "Bench Press 3x6-8",
    "DB Walking Lunge 3x12 ea",
    "1-Arm DB Row 3x10 ea",
    "Triceps Pushdown 2x12",
    "Biceps Curl 2x12",
    "Russian Twist 3x25 reps",
    "Treadmill Intervals 10 min (slightly faster)",
    "Cool-Down: Stretch chest, shoulders, calves",
  ],
  "Week 3 - Day 3": [
    "Warm-Up: 5 min elliptical, banded leg openers",
    "Barbell Deadlift 3x6-8",
    "Lat Pulldown 3x10",
    "Incline DB Press 3x10",
    "Step-Ups 3x10 ea",
    "Side Plank 3x40s ea",
    "Rowing Intervals 12 min",
    "Cool-Down: Deep stretch lower back and legs",
  ],
  "Week 4 - Day 1": [
    "Warm-Up: 5 min jog, dynamic leg swings, arm circles",
    "Back Squat 3x8",
    "Bent-Over Row 3x10",
    "DB Overhead Press 3x10",
    "Leg Curl 3x12",
    "Plank 3x45s",
    "Elliptical 12 min (RPE 7)",
    "Cool-Down: Hamstring, glute, quad stretch",
  ],
  "Week 4 - Day 2": [
    "Warm-Up: 5 min rowing, shoulder circles, mobility",
    "Bench Press 3x6-8",
    "DB Walking Lunge 3x12 ea",
    "1-Arm DB Row 3x10 ea",
    "Triceps Pushdown 2x12",
    "Biceps Curl 2x12",
    "Russian Twist 3x30 reps",
    "Treadmill Intervals 12 min (incline 2–4%)",
    "Cool-Down: Upper back and hip mobility",
  ],
  "Week 4 - Day 3": [
    "Warm-Up: 5 min elliptical, jump rope, glute bridges",
    "Barbell Deadlift 3x6-8",
    "Lat Pulldown 3x10",
    "Incline DB Press 3x10",
    "Step-Ups 3x10 ea",
    "Side Plank 3x45s ea",
    "Rowing Intervals 12 min",
    "Cool-Down: Full posterior chain stretch",
  ],
  "Week 5 - Day 1": [
    "Warm-Up: 5 min treadmill/bike + dynamic prep (band pull-aparts, shoulder dislocations)",
    "Barbell Back Squat 4x6-8 (heavier weight or added 4th set from Phase 1)",
    "Superset 1A: Seated Cable Row 3x10 (close-grip, focus on back squeeze)",
    "Superset 1B: Arnold DB Press 3x10 (rotate palms during press)",
    "Superset 2A: DB Romanian Deadlift 3x10 (focus on hamstring stretch)",
    "Superset 2B: Hanging Knee Raise 3x12 (strict form)",
    "Cardio: Treadmill Incline Walk 10 min (5-8% grade, brisk pace RPE 7/10)",
    "Cool-Down: Full body mobility work and stretching",
  ],
  "Week 5 - Day 2": [
    "Warm-Up: 5 min rowing + mobility (band work for shoulders/chest)",
    "DB Bench Press 3x8 (heavy, challenging weight)",
    "Superset 1A: Bulgarian Split Squat 3x8 each leg (focus on depth)",
    "Superset 1B: Pull-Ups 3xAMAP (or assisted for 8-10 reps)",
    "Superset 2A: EZ-Bar Curl 2x10 (controlled tempo)",
    "Superset 2B: Overhead Triceps Extension 2x10",
    "Core: Bicycle Crunch 3x20 each side",
    "Cardio: Rowing HIIT - 12 rounds (30s sprint/30s easy)",
    "Cool-Down: Static stretches emphasizing worked areas",
  ],
  "Week 5 - Day 3": [
    "Warm-Up: 5 min elliptical + movement prep for deadlifts",
    "Barbell Deadlift 4x6 (heavy weight, perfect form)",
    "Superset 1A: Dips 3x10 (weighted if possible)",
    "Superset 1B: One-Arm DB Row 3x10 each arm",
    "Superset 2A: Standing Calf Raise 3x15 (full range of motion)",
    "Superset 2B: Dead Bug 3x12 each side (maintain core control)",
    "Cardio: Elliptical HIIT 3 rounds (2 min hard/1 min easy)",
    "Cool-Down: Thorough stretch focusing on posterior chain",
  ],
  "Week 6 - Day 1": [
    "Warm-Up: 5 min treadmill jog, mobility drills",
    "Barbell Back Squat 4x6-8",
    "Seated Cable Row 3x10",
    "Arnold DB Press 3x10",
    "DB Romanian Deadlift 3x10",
    "Hanging Knee Raise 3x15",
    "Incline Walk 12 min",
    "Cool-Down: Lower body and shoulder stretch",
  ],
  "Week 6 - Day 2": [
    "Warm-Up: 5 min rowing or bike",
    "DB Bench Press 3x8",
    "Bulgarian Split Squat 3x8 ea",
    "Pull-Ups or Assisted 3 sets",
    "EZ-Bar Curl 2x10",
    "Overhead Triceps Extension 2x10",
    "Bicycle Crunch 3x24",
    "Rowing Intervals: 30s hard / 30s easy x14",
    "Cool-Down: Chest, back, glute stretch",
  ],
  "Week 6 - Day 3": [
    "Warm-Up: 5 min elliptical or jump rope",
    "Barbell Deadlift 4x6",
    "Dips (weighted if possible) 3x10",
    "1-Arm DB Row 3x10 ea",
    "Standing Calf Raise 3x15",
    "Dead Bug 3x15 ea",
    "Elliptical HIIT 2min/1min x4",
    "Cool-Down: Stretch hamstrings, glutes, core",
  ],
  "Week 7 - Day 1": [
    "Warm-Up: 5 min walk + dynamic lunges",
    "Barbell Back Squat 4x6-8",
    "Seated Cable Row 3x10",
    "Arnold DB Press 3x10",
    "DB Romanian Deadlift 3x10",
    "Hanging Knee Raise 3x15",
    "Incline Walk 12 min (6–8% incline)",
    "Cool-Down: Full body foam roll and stretch",
  ],
  "Week 7 - Day 2": [
    "Warm-Up: 5 min rowing + mobility",
    "DB Bench Press 3x8",
    "Bulgarian Split Squat 3x10 ea",
    "Pull-Ups 3 sets (or chin-ups)",
    "EZ-Bar Curl 2x12",
    "Overhead Triceps Extension 2x12",
    "Bicycle Crunch 3x26",
    "Rowing Intervals: 30s sprint / 30s recovery x15",
    "Cool-Down: Stretch hips, back, shoulders",
  ],
  "Week 7 - Day 3": [
    "Warm-Up: 5 min elliptical",
    "Barbell Deadlift 4x6",
    "Dips 3x12",
    "1-Arm DB Row 3x10 ea",
    "Standing Calf Raise 3x15",
    "Dead Bug 3x15 ea",
    "Elliptical HIIT 2min/1min x5",
    "Cool-Down: Stretch quads, glutes, hamstrings",
  ],
  "Week 8 - Day 1": [
    "Warm-Up: 5 min walk or bike",
    "Barbell Back Squat 4x6",
    "Seated Cable Row 3x12",
    "Arnold DB Press 3x12",
    "DB Romanian Deadlift 3x12",
    "Hanging Knee Raise 3x15",
    "Incline Walk 12 min (challenging incline)",
    "Cool-Down: Stretch hips, glutes, back",
  ],
  "Week 8 - Day 2": [
    "Warm-Up: 5 min rowing or elliptical",
    "DB Bench Press 3x10",
    "Bulgarian Split Squat 3x10 ea",
    "Pull-Ups or Assisted 3xAMAP",
    "EZ-Bar Curl 2x15",
    "Overhead Triceps Extension 2x15",
    "Bicycle Crunch 3x30",
    "Rowing Intervals: 30s sprint / 30s easy x16",
    "Cool-Down: Full upper body stretch",
  ],
  "Week 8 - Day 3": [
    "Warm-Up: 5 min jog or stairs",
    "Barbell Deadlift 4x5",
    "Dips 3x12",
    "1-Arm DB Row 3x12 ea",
    "Standing Calf Raise 3x20",
    "Dead Bug 3x20 ea",
    "Elliptical Intervals 2min/1min x5",
    "Cool-Down: Stretch hamstrings, shoulders, core",
  ],
  "Week 9 - Day 1": [
    "Warm-Up: 5 min jog + explosive prep (squat-to-stands, jumping jacks, arm swings)",
    "Barbell Back Squat 4x6 (heaviest weight of program, ~2 min rest)",
    "Tri-Set 1A: Barbell Row 3x10 (controlled form)",
    "Tri-Set 1B: Push-Ups 3x15 (full range)",
    "Tri-Set 1C: Plank 3x60s (maximum tension)",
    "Power Finisher: Jump Squats 2x10 (explosive but controlled)",
    "Cardio: Treadmill Tempo Run 10 min (RPE 8-9/10 sustained)",
    "Cool-Down: Thorough stretch + recovery work",
  ],
  "Week 9 - Day 2": [
    "Warm-Up: 5 min bike/rope + power preparation",
    "Barbell Bench Press 4x5 (maximum strength focus)",
    "Tri-Set 1A: Box Jumps 3x8 (safe height, perfect landings)",
    "Tri-Set 1B: Pull-Ups 3x10 (full range)",
    "Tri-Set 1C: Mountain Climbers 3x20 each leg (fast pace)",
    "Superset 1A: Hammer Curl 2x15 (controlled)",
    "Superset 1B: Triceps Pushdown 2x15",
    "Core Finisher: Ab Wheel 2x10 (full extension)",
    "Cardio: Elliptical Sprint Intervals 10 rounds (20s sprint/40s easy)",
    "Cool-Down: Upper body mobility work",
  ],
  "Week 9 - Day 3": [
    "Warm-Up: 5 min row + hip/shoulder mobility",
    "Barbell Deadlift 3x5 (peak strength, perfect form)",
    "Tri-Set 1A: DB Push Press 3x8 (explosive drive)",
    "Tri-Set 1B: Rear Delt Fly 3x12 (shoulder control)",
    "Tri-Set 1C: Cable Woodchopper 3x12 each side",
    "Superset 1A: Back Extension 3x15 (squeeze at top)",
    "Superset 1B: Burpees 2x10 (explosive but controlled)",
    "Cardio: Rowing Pyramid Ladder (increase work intervals)",
    "Cool-Down: Full recovery stretching protocol",
  ],
  "Week 10 - Day 1": [
    "Warm-Up: 5 min jog + explosive movement prep (jump rope, high knees)",
    "Barbell Back Squat 4x6 (maintain heavy weight, perfect form)",
    "Tri-Set 1A: Barbell Row 3x12 (increase reps from Week 9)",
    "Tri-Set 1B: Push-Ups 3x20 (increase volume)",
    "Tri-Set 1C: Plank 3x60s (maximum tension)",
    "Power Finisher: Jump Squats 2x12 (increase reps)",
    "Cardio: Treadmill Tempo Run 10 min (faster pace than Week 9)",
    "Cool-Down: Full mobility and recovery work",
  ],
  "Week 10 - Day 2": [
    "Warm-Up: 5 min rowing + dynamic power preparation",
    "Barbell Bench Press 4x5 (peak strength, controlled negatives)",
    "Complex 1A: Box Jumps 3x10 (explosive power)",
    "Complex 1B: Pull-Ups 3xAMAP (maximum effort)",
    "Complex 1C: Mountain Climbers 3x25 each side (sprint pace)",
    "Superset 1A: Hammer Curl 2x15 (maintain form)",
    "Superset 1B: Overhead Triceps Extension 2x15",
    "Core Finisher: Ab Wheel 2x12 (increase reps)",
    "Cardio: Elliptical HIIT 14 rounds (30s sprint/30s recovery)",
    "Cool-Down: Thorough upper body stretch work",
  ],
  "Week 10 - Day 3": [
    "Warm-Up: 5 min cardio + movement preparation",
    "Barbell Deadlift 3x5 (maximum weight with perfect form)",
    "Tri-Set 1A: DB Push Press 3x8 (explosive power)",
    "Tri-Set 1B: Reverse Fly 3x12 (controlled tension)",
    "Tri-Set 1C: Cable Woodchopper 3x15 each side",
    "Superset 1A: Back Extension 3x15 (full range)",
    "Superset 1B: Burpees 2x12 (increase intensity)",
    "Cardio: Advanced Rowing Pyramid (increase work periods)",
    "Cool-Down: Complete recovery protocol",
  ],
  "Week 11 - Day 1": [
    "Warm-Up: 5 min dynamic + power prep (jump rope, dynamic lunges, explosive squats)",
    "Barbell Back Squat 4x6 (peak intensity, maintain perfect form)",
    "Complex 1A: Barbell Row 3x12 (increase weight from Week 10)",
    "Complex 1B: Push-Ups 3x25 (increase endurance)",
    "Complex 1C: Plank 3x60s (maximum core engagement)",
    "Power Circuit: Jump Squats 2x15 (explosive power)",
    "Cardio: Treadmill Tempo Run 12 min (peak endurance)",
    "Cool-Down: Full mobility + recovery work",
  ],
  "Week 11 - Day 2": [
    "Warm-Up: 5 min cardio + advanced mobility",
    "Barbell Bench Press 4x5 (peak strength phase)",
    "Complex 1A: Box Jumps 3x12 (power focus)",
    "Complex 1B: Pull-Ups 3xAMAP (maximum effort)",
    "Complex 1C: Mountain Climbers 3x30 each side",
    "Superset 1A: Hammer Curl 2x15 (peak tension)",
    "Superset 1B: Overhead Triceps Extension 2x15",
    "Core Finisher: Ab Wheel 2x15 (full range)",
    "Cardio: Elliptical HIIT 16 rounds (30s/30s - peak intensity)",
    "Cool-Down: Thorough recovery protocol",
  ],
  "Week 11 - Day 3": [
    "Warm-Up: 5 min intensive movement prep",
    "Barbell Deadlift 3x5 (peak power phase)",
    "Complex 1A: DB Push Press 3x10 (explosive power)",
    "Complex 1B: Reverse Fly 3x15 (shoulder stability)",
    "Complex 1C: Cable Woodchopper 3x15 each side",
    "Circuit: Back Extension 3x15 + Burpees 2x15",
    "Cardio: Advanced Rowing Pyramid (30s-60s ladder)",
    "Cool-Down: Full-body recovery work",
  ],
  "Week 12 - Day 1": [
    "Warm-Up: 5 min intensive power preparation (jumping, dynamic mobility)",
    "Barbell Back Squat 4x6 (program peak weight attempt)",
    "Complex 1A: Barbell Row 3x15 (endurance focus)",
    "Complex 1B: Push-Ups 3x30 (maximum volume)",
    "Complex 1C: Plank 3x60s (peak stability test)",
    "Power Finisher: Jump Squats 2x15 (explosive power)",
    "Challenge: Treadmill 2-mile test (best time effort)",
    "Cool-Down: Complete lower body recovery protocol",
  ],
  "Week 12 - Day 2": [
    "Warm-Up: 5 min high-intensity preparation",
    "Barbell Bench Press 4x5 (program peak weight)",
    "Complex 1A: Box Jumps 3x15 (power endurance)",
    "Complex 1B: Pull-Ups 3xAMAP (maximum effort)",
    "Complex 1C: Mountain Climbers 3x35 each side",
    "Superset 1A: Hammer Curl 2x15 (peak form)",
    "Superset 1B: Overhead Triceps Extension 2x15",
    "Core Challenge: Ab Wheel 3x12 (full extension)",
    "Cardio: Elliptical Peak HIIT 18 rounds (30s/30s)",
    "Cool-Down: Full upper body recovery work",
  ],
  "Week 12 - Day 3": [
    "Warm-Up: 5 min final preparation protocol",
    "Barbell Deadlift 3x5 (program peak attempt)",
    "Complex 1A: DB Push Press 3x10 (maximum power)",
    "Complex 1B: Reverse Fly 3x15 (perfect control)",
    "Complex 1C: Cable Woodchopper 3x20 each side",
    "Final Circuit: Back Extension 3x15 + Burpees 3x15",
    "Cardio: Ultimate Rowing Pyramid Challenge",
    "Cool-Down: Complete program recovery protocol",
  ],
};
